# Generated by Django 5.0 on 2023-12-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0004_create_group_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="student",
            field=models.ManyToManyField(
                blank=True, default=None, to="mentorship.student"
            ),
        ),
    ]
