# Generated by Django 5.0.1 on 2024-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing_system", "0008_create_attempt_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="selected_answers",
            field=models.ManyToManyField(blank=True, to="testing_system.answer"),
        ),
    ]
